config/routes.rb
Rails.application.routes.draw do
  root "sessions#index"
  resources :sessions
  resources :users
  delete '/logout' => "sessions#destroy", as: 'logout'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	before_save :doj_validate
  has_secure_password
  validates :fname, presence:true, length: { maximum: 20 }, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/}
  validates :lname, presence:true, length: { maximum: 20 }, format: {with: /\A[a-zA-Z]+\z/}
  validates :ename, presence:true, length: { maximum: 20 }, format: {with: /\A[a-zA-Z]+(?: [a-zA-Z]+)?\z/}
  validates :contact, presence:true
  validates :contact, length: { minimum: 10, maximum: 10}
  validates :econtact, presence:true
  validates :econtact, length: { minimum: 10, maximum: 10}
  validates :email, presence:true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :age, presence:true, numericality: { greater_than_or_equal_to: 18}
  validates :pincode, presence:true, length:  { minimum: 6, maximum: 10}
  validates :doj, presence:true
  
  
	# def doj_validate
	#   if (doj.present? && doj > Date.today)
	#     errors.add(:date, 'not in past or present')
	#   end
	# end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(userparams[:email])
    if user && user.authenticate(userparams[:password]) && user.role=='admin'
      session[:user_type]='admin'
      redirect_to '/users'
    elsif user && user.authenticate(userparams[:password])
      session[:user_type]='user'
      session[:user_id]=user.id
      redirect_to user
    else
      render 'index'
    end
  end

  def destroy
    session[:user_type]=nil
    session[:user_id]=nil
    redirect_to root_path
  end

  private

  def userparams
    params.require(:user).permit(:email,:password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to @user, notice: 'User was successfully created.' 
      else
        render :new
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :age, :doj, :contact, :sal, :salpm, :address, :city, :state, :country, :pincode, :blood, :ename, :econtact, :pskill, :sskill1, :sskill2, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asha1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <%# if user.errors.any? %>
    <!-- <div id="error_explanation">
      <h2><%#= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <%# user.errors.full_messages.each do |message| %>
          <li><%#= message %></li>
        <% #end %>
      </ul>
    </div> -->
  <%# end %>
  <style>
    input[type=text] {
   width: 20%;
   padding: 5px 5px;
   box-sizing: border-box;
  }
  </style>
  <div class="field">
    <%= form.label :fname ,class: "required" %>
    <%= form.text_field :fname %><span style="color:red;"><%= @user.errors[:fname][0] rescue nil%></span>
  </div>

  <div class="field">
    <%= form.label :lname ,class: "required" %>
    <%= form.text_field :lname %><span style="color:red;"><%= @user.errors[:lname][0] rescue nil%></span>
  </div>

  <div class="field">
    <%= form.label :age , class: "required" %>
    <%= form.number_field :age %><span style="color:red;"><%= @user.errors[:age][0] rescue nil%></span>
  </div>

  <div class="field">
    <%= form.label :doj %>
    <%= form.date_field :doj , :max => Date.today %>
  </div>

  <div class="field">
    <%= form.label :contact ,class: "required"%>
    <%= form.text_field :contact %><span style="color:red;"><%= @user.errors[:contact][0] rescue nil%></span>
  </div>

  <div class="field">
    <%= form.label :sal , :required => true,class: "required"%>
    <%= form.text_field :sal %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.select :state, ['State','Andaman and Nicobar Islands','Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chandigarh','Chhattisgarh','Dadra and Nagar Haveli','Daman and Diu','Delhi','Goa','Gujarat','Haryana','Himachal Pradesh','Jammu and Kashmir','Jharkhand','Karnataka','Kerala','Ladakh','Lakshadweep','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Puducherry','Punjab','Rajasthan','Sikkim','Tamil Nadu''Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'] %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.select :country, ['Country','India'] %>
  </div>

  <div class="field">
    <%= form.label :pincode ,class: "required" %>
    <%= form.text_field :pincode %>
  </div>

  <div class="field">
    <%= form.label :blood %>
    <%= form.select :blood , ['A+','B+','O+','AB+','AB-','A-','B-','o-']  %>
  </div>

  <div class="field">
    <%= form.label :ename , class: "required" %>
    <%= form.text_field :ename %><span style="color:red;"><%= @user.errors[:ename][0] rescue nil%></span>
  </div>

  <div class="field">
    <%= form.label :econtact , class: "required" %>
    <%= form.text_field :econtact %><span style="color:red;"><%= @user.errors[:contact][0] rescue nil%></span>
  </div>

  <div class="field">
    <%= form.label :pskill %>
    <%= form.text_field :pskill %>
  </div>

  <div class="field">
    <%= form.label :sskill1 %>
    <%= form.text_field :sskill1 %>
  </div>

  <div class="field">
    <%= form.label :sskill2 %>
    <%= form.text_field :sskill2 %>
  </div>

  <div class="field">
    <%= form.label :email , class: "required" %>
    <%= form.text_field :email %><span style="color:red;"><%= @user.errors[:email][0] rescue nil%></span>
  </div>

  <div class="field">
    <%= form.label :password , class: "required" %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation , class: "required" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <ul>
      <li><a href="#"><h1><b>EXALOGIC</b></h1></a></li>
      <li><a href="/users">Home</a></li>
      <li><a href="/users/new">Create Users</a></li>
      <li><%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure??"}%>
    </li>
    </ul>
    <div style="margin-left:25%;padding:1px 16px;height:1000px;">
      <h1>Editing User</h1>

      <%= render 'form', user: @user %>

      <%= link_to 'Show', @user %> |
      <%= link_to 'Back', users_path %>
    </div>

  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

  </head>
  <body>


    <ul>
      <li><a href="#"><h1><b>EXALOGIC</b></h1></a></li>
      <li><a class="active" href="#">Home</a></li>
      <li><a href="/users/new">Create Users</a></li>
      <li><%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure??"}%>
</li>
    </ul>

    <div style="margin-left:25%;padding:1px 16px;height:1000px;">
      <p id="notice"><%= notice %></p>

      <h1>All Users</h1>

      <table id="customers">
        <thead>
          <tr>
            <th>Fname</th>
            <th>Lname</th>
            <th>Age</th>
            <th>Contact</th>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <% if user.role!='admin'%>
            <tr>
              <td><%= user.fname %></td>
              <td><%= user.lname %></td>
              <td><%= user.age %></td>
              <td><%= user.contact %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Show', user %></td>
              <td><%= link_to 'Edit', edit_user_path(user) %></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end%>
          <% end %>
        </tbody>
      </table>
</div>
  </body>
</html>

app/views/users/new.html.erb
<ul>
  <li><a href="#"><h1><b>EXALOGIC</b></h1></a></li>
  <li><a href="/users">Home</a></li>
  <li><a class="active" href="/users/new">Create Users</a></li>
  <li><%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure??"}%>
</li>
</ul>
<div style="margin-left:25%;padding:1px 16px;height:1000px;">

  <%= render 'form', user: @user %>

</div>

app/views/users/show.html.erb
<ul>
  <li><a href="#"><h1><b>EXALOGIC</b></h1></a></li>
  <% if session[:user_type]=='admin'%>
    <li><a class="active" href="/users">Home</a></li>
    <li><a href="/users/new">Create Users</a></li>
  <% else %>
    <li><a class="active" href="#">Home</a></li>
  <% end%>

  <li><%= link_to "Logout", logout_path, method: :delete, data: {confirm: "Are you sure??"}%>
</li>
<div class="">
</ul>
<div style="margin-left:25%;padding:1px 16px;height:1000px;">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Fname:</strong>
    <%= @user.fname %>
  </p>

  <p>
    <strong>Lname:</strong>
    <%= @user.lname %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= @user.age %>
  </p>

  <p>
    <strong>Doj:</strong>
    <%= @user.doj %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= @user.contact %>
  </p>

  <p>
    <strong>Sal:</strong>
    <%= @user.sal.to_i %>
  </p>

  <p>
    <strong>Salpm:</strong>
    <%= @user.salpm %><%= (@user.sal/12).to_i%>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @user.address %>
  </p>

  <p>
    <strong>City:</strong>
    <%= @user.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= @user.state %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= @user.country %>
  </p>

  <p>
    <strong>Pincode:</strong>
    <%= @user.pincode %>
  </p>

  <p>
    <strong>Blood:</strong>
    <%= @user.blood %>
  </p>

  <p>
    <strong>Ename:</strong>
    <%= @user.ename %>
  </p>

  <p>
    <strong>Econtact:</strong>
    <%= @user.econtact %>
  </p>

  <p>
    <strong>Pskill:</strong>
    <%= @user.pskill %>
  </p>

  <p>
    <strong>Sskill1:</strong>
    <%= @user.sskill1 %>
  </p>

  <p>
    <strong>Sskill2:</strong>
    <%= @user.sskill2 %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  <% if session[:user_type]=='admin'%>
    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Back', users_path %>
  <% end%>

</div>